---
title: "Analysis"
author: "Orion Bowers"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
library(tidyverse)
library(sf)
library(forecast)
library(ranger)
library(workflows)
library(parsnip)
library(recipes)
library(zoo)
library(multcomp)
library(car)

crimes <- read.csv('crimes_cleaned.csv')

unique_crimes <- names(table(crimes$Primary.Type))[table(crimes$Primary.Type) < 7]
crimes$Primary.Type[crimes$Primary.Type %in% unique_crimes] <- "OTHER"
crimes$new_date <- as.Date(crimes$new_date)

unique_ward <- names(table(crimes$Ward))[table(crimes$Ward) < 15706]
# 15706
crimes$Ward[crimes$Ward %in% unique_ward] <- "OTHER"

crimes$isFullMoon <- as.numeric(crimes$moonphase < .55 & crimes$moonphase > .45)
```

## EDA

```{r}
counts <- crimes %>%
  group_by(new_date) %>%
  summarise(Count = n()) %>% ungroup()

CrimeCountsFull <- ggplot(counts, aes(x = new_date, y=Count)) +
  geom_point() +
  geom_smooth(se=F) +
  labs(title="Total Crimes by Time", x="Time",y="Total crimes") +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y")
  
ggsave("CrimeCounts.png",plot=CrimeCountsFull, width=14,height=7)
```


```{r}
# cc <- crimes %>%
#   filter(new_date < "2015-01-01")
# 
# counts <- cc %>%
#   group_by(new_date) %>%
#   summarise(Count = n()) %>% ungroup()
# 
# 
# CrimeCountsHalf <- ggplot(counts, aes(x = new_date, y=Count)) +
#   geom_point() +
#   geom_smooth(se=F) +
#   labs(title="Total Crimes by Time", x="Time",y="Total crimes") +
#   scale_x_date(date_breaks = "1 year", date_labels = "%Y")
#   
# ggsave("CrimeCountsHalf.png",plot=CrimeCountsHalf, width=14,height=7)
```

```{r}
crime_counts <- crimes %>% count(Primary.Type) %>% arrange(n)
crimes$Primary.Type <- factor(crimes$Primary.Type, levels = crime_counts$Primary.Type)

commonCrimes <- ggplot(crimes, aes(y = Primary.Type, fill=Primary.Type)) + geom_bar() + theme(legend.position = "none")
ggsave("CommonCrimes.png",commonCrimes, width=10)
```

```{r}
crimes %>% group_by(Beat) %>% summarise(Count = n())
crimes %>% group_by(Ward) %>% summarise(Count = n())
crimes %>% group_by(Community.Area) %>% summarise(Count = n())

# Proportion of arrests for crimes
sum(crimes$Arrest)/length(crimes$Arrest)

# Proportion of domestic crimes
sum(crimes$Domestic)/length(crimes$Domestic)
```

```{r}
crimes_sm <- crimes[!is.na(crimes$Latitude),]
crimes_sm <- crimes_sm %>%
   filter(Latitude > 40) %>% mutate(Ward = as.factor(Ward))
crimes_sf <- st_as_sf(crimes_sm, coords = c("Longitude", "Latitude"), crs = 4326)

# Visualize with ggplot
crime_cluster <- ggplot() +
  geom_sf(data = crimes_sf, aes(color=Ward)) +
  theme_minimal() +
  labs(title = "Crime Clustering in Chicago",
       subtitle = "Based on Longitude and Latitude")
ggsave("CrimeCluster.png", crime_cluster,width=10)

crimes_sm <- crimes[!is.na(crimes$Latitude),]
crimes_sm <- crimes_sm %>%
   filter(Latitude > 40 & new_date >= "2015-01-1") %>% mutate(Ward = as.factor(Ward))
crimes_sf <- st_as_sf(crimes_sm, coords = c("Longitude", "Latitude"), crs = 4326)

# Visualize with ggplot
crime_cluster2 <- ggplot() +
  geom_sf(data = crimes_sf, aes(color=Ward)) +
  theme_minimal() +
  labs(title = "Crime Clustering in Chicago",
       subtitle = "Based on Longitude and Latitude")
ggsave("CrimeCluster2.png", crime_cluster2,width=10)

summary(crimes_sm)
```

## Nonsensical code

```{r}
## Trying to get an ARIMA model to work
# 
# 
# crimes$Year = year(as.Date(crimes$new_date))
# crimes$Month = month(as.Date(crimes$new_date))
# crimes$Day = day(as.Date(crimes$new_date))
# crimes$YrMon <- crimes$Year + (crimes$Month)/12 + (crimes$Day)/365
# 
# crimes_acf <- crimes %>%
#   group_by(new_date) %>%
#   summarise(
#     Crimes = n(),
#     YrMon = mean(YrMon),
#     Location.Description = get_mode(Location.Description),
#     Beat = get_mode(as.factor(Beat)),
#     Ward = get_mode(as.factor(Ward)),
#     Community.Area = get_mode(as.factor(Community.Area)),
#     Holiday = replace_na_with_empty(Title),
#     feelslikemax = mean(feelslikemax),
#     feelslikemin = mean(feelslikemin),
#     dew = mean(dew),
#     humidity = mean(humidity),
#     precip = mean(precip),
#     preciptype = replace_na_with_empty(preciptype),
#     snow = mean(snow),
#     snowdepth = mean(snowdepth),
#     windgust = did_happen(windgust),
#     windspeed = mean(windspeed),
#     cloudcover = get_mode(cloudcover),
#     visibility = get_mode(visibility),
#     # sunriseTime = get_mode(sunriseTime),
#     # sunsetTime = get_mode(sunsetTime),
#     moonphase = get_mode(moonphase),
#     weekend = get_mode(weekend)
#   )
# 
# # Don't include time, arrest, domestic, latitude, longitude, sunset or sunrise
# 
# 
# 
# crimes_acf <- crimes %>%
#   group_by(YrMon) %>%
#   summarise(
#     Crimes = n(),
#     # YrMon = mean(YrMon)
#     # moonphase = get_mode(moonphase)
#     precip = mean(precip),
#     snow = mean(snow)
#   )
# 
# ggAcf(x=crimes_acf$Crimes, lag.max=50)
# 
# crimes_acf$Crimes <- (crimes_acf$Crimes - mean(crimes_acf$Crimes))/sd(crimes_acf$Crimes)
# 
# crimes_acf$precip <- (crimes_acf$precip - mean(crimes_acf$precip))/sd(crimes_acf$precip)
# crimes_acf$snow <- (crimes_acf$snow - mean(crimes_acf$snow))/sd(crimes_acf$snow)
# 
# my.ts <- ts(data=crimes_acf$Crimes, start=c(2010,1), frequency=365.25)
# date <- c(2010,1)
# ts(data=crimes_acf$Crimes,start=date,frequency=365+1* (!date[1]%%400 || ((date[1]%%100)&&!date[1]%%4) ))
# years <- as.numeric(format(time(my.ts), "%Y"))
# years <- as.numeric(format(time(my.ts), "%Y"))
# years <- as.numeric(format(time(my.ts), "%Y"))
# 
# X <- model.matrix(Crimes~Beat+Holiday+feelslikemax+feelslikemin+humidity+precip+snow+snowdepth+windgust+windspeed+visibility+moonphase+weekend, data=crimes_acf)
# X <- model.matrix(Crimes~-1+precip+snow,data=crimes_acf)
# 
# X
# # YrMon+Location.Description+Beat+Ward+Community.Area+Holiday+feelslikemax+feelslikemin+dew+humidity+precip+snow+snowdepth+windgust+windspeed+cloudcover+visibility+moonphase+weekend
# Beat+Holiday+feelslikemax+feelslikemin+humidity+precip+snow+snowdepth+windgust+windspeed+visibility+moonphase+weekend
# 
# ggplot(data=crimes_acf, aes(x=YrMon,y=Crimes))+geom_point()
# 
# my.ts
# ggPacf(diff(crimes_acf$Crimes))
# 
# cc.aarima <- auto.arima(my.ts, max.p= 3, max.q= 3, max.P=3, 
#                         max.Q=3, max.d=2, max.D=2, ic="aic", 
#                         stepwise=FALSE, xreg=X)
# Arima(my.ts, order=c(5,1,1), xreg=X)
# tail(crimes)
```


```{r}
## Random Forest
# recipe <- 
# 
# forest <- rand_forest(mtry=tune(), min_n=tune(), trees=500) %>%
#   set_engine("ranger") %>% set_mode("classification")
```

## Fitting ARIMA Model

```{r}
get_mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

did_happen <- function(x) {
  !all(is.na(x))
}

replace_na_with_empty <- function(x) {
  ifelse(all(is.na(x)), "None", ifelse(is.na(x), "None", as.character(x)))
}

nicky_Holiday <- function(x) {
  # ifelse(get_mode(x) %in% c("Christmas Day", "Thanksgiving Day", "New Year's Day", "Independence Day"), 1, 0)
  ifelse(get_mode(x) %in% c("Christmas Day","New Year's Day"), 1, 0)
}

crimes_acf <- crimes %>%
  group_by(new_date) %>%
  summarise(
    Crimes = n(),
    # YrMon = mean(YrMon),
    Location.Description = get_mode(Location.Description),
    Beat = get_mode(as.factor(Beat)),
    Ward = get_mode(as.factor(Ward)),
    Community.Area = get_mode(as.factor(Community.Area)),
    # Holiday = replace_na_with_empty(Title),
    # Holiday = as.numeric(did_happen(Title)),
    Holiday = nicky_Holiday(Title),
    feelslikemax = mean(feelslikemax),
    feelslikemin = mean(feelslikemin),
    dew = mean(dew),
    humidity = mean(humidity),
    precip = mean(precip),
    # preciptype = replace_na_with_empty(preciptype),
    snow = mean(snow),
    snowdepth = mean(snowdepth),
    windgust = as.numeric(did_happen(windgust)),
    windspeed = mean(windspeed),
    cloudcover = get_mode(cloudcover),
    visibility = get_mode(visibility),
    # sunriseTime = get_mode(sunriseTime),
    # sunsetTime = get_mode(sunsetTime),
    # moonphase = get_mode(moonphase),
    isFullMoon = mean(isFullMoon),
    weekend = get_mode(weekend)
  )

crimes_acf <-  crimes_acf %>% filter(new_date >= "2014-12-15")


imputed_mean <- mean(crimes_acf$Crimes[day(crimes_acf$new_date) == "31" & month(crimes_acf$new_date) == "5" & year(crimes_acf$new_date) != "2020"])

max_crime_row <- which.max(crimes_acf$Crimes)
crimes_acf[max_crime_row,]$Crimes = as.integer(imputed_mean)


zoo_data <- zoo(crimes_acf$Crimes, crimes_acf$new_date)

# Adding more than 11 factors seems to be grumpy
# Remove Preciptype
# Holiday, Community Area, Ward, Beat, Location.Description is grumpy for no reason (Too big of an X matrix?)
X <- model.matrix(Crimes~-1+isFullMoon+Ward+Holiday+feelslikemax+feelslikemin+dew+precip+snow+snowdepth+windgust+windspeed+cloudcover+visibility+weekend,data=crimes_acf)
X <- X[,-5]
# Want Holiday, Beat/Ward

c.lm <- Arima(zoo_data, order=c(2,0,2), xreg=X)
# Ideal is 3,1,2. We did 3,0,2 since it increased the AIC by 10 but helps interpretability
# cc.aarima <- auto.arima(zoo_data, max.p= 5, max.q= 3, max.P=3,
#                          max.Q=3, max.d=2, max.D=2, ic="aic",
#                         stepwise=FALSE, xreg=X)

summary(c.lm)
confint(c.lm)

# True AIC: 37562.49
# Imputed AIC: 37457.27

# 2010 AIC with Ward: 37438.11
# 2012: 31989.57
# 2014: 26509.15
# 2014, 06: 25376.79
# 2014, 09: 24701.87
# 2014, 12.01: 24016.19
# 2014, 12.15: 23916.19

# 2014, 12.15 (0,0,2): 24894.93
# 2014, 12.155 (0,0,2) With Major Holiday: 24890.32
# Most recent: 23909.25
```
## Crimes_acf by day
```{r}
CountCrimes2015 <- ggplot(crimes_acf, aes(y = Crimes, x=new_date)) + geom_line() + labs(title = "Daily Crime in Chicago", x="Date")
ggsave("CountCrimes2015.png",CountCrimes2015, width=15)
```


## Validating Our Feelings/Assumptions

```{r message=F}
# Linearity - Good
c.lm.dummy <- lm(Crimes~-1+isFullMoon+Holiday+feelslikemax+feelslikemin+dew+precip+snow+snowdepth+windgust+windspeed+cloudcover+visibility+weekend,data=crimes_acf)
avPlots(c.lm.dummy, ask = FALSE)

# Independence - Questionable but mostly good
init_acf <- ggAcf(crimes_acf$Crimes, lag.max=1000) + labs(title="ACF Plot for Crime Counts")
model_acf <- ggAcf(c.lm$residuals, lag.max=1000) + labs(title="ACF Plot for Residuals")
ggsave("InitACF.png",init_acf, width=10)
ggsave("ModelACF.png",model_acf, width=10)

# Normality of Residuals - Several outliers, the rest is happy
hist_res <- ggplot(mapping=aes(x=resid(c.lm))) + geom_histogram() + labs(title="Histogram of Residuals", x="Residuals")
ggsave("HistogramOfResiduals.png",hist_res, width=10)

# Equal Variance - No obvious pattern
fit_vs_resid <- ggplot(mapping=aes(y=resid(c.lm),x=fitted(c.lm))) + geom_point() + labs(title="Fitted Values vs Residuals", y="Residuals", x="Fitted Values")
ggsave("FittedvsResiduals.png",fit_vs_resid, width=10)
```


```{r message=F}
# Cross Validation
n.cv <- nrow(X)

test.set <- crimes_acf[2210:nrow(crimes_acf),] # Jan 1, 2021 - Feb 24, 2024
train.set <- crimes_acf[-(2210:nrow(crimes_acf)),]
# ts_train <- ts(data=train.set$AnnAnom, start=c(1950,1), frequency=12)
ts_train <- zoo(train.set$Crimes, train.set$new_date)
X_train <- model.matrix(Crimes~-1+isFullMoon+Ward+Holiday+feelslikemax+feelslikemin+dew+precip+snow+snowdepth+windgust+windspeed+cloudcover+visibility+weekend,data=train.set)
X_train <- X_train[,-5]
X_test <- model.matrix(Crimes~-1+isFullMoon+Ward+Holiday+feelslikemax+feelslikemin+dew+precip+snow+snowdepth+windgust+windspeed+cloudcover+visibility+weekend,data=test.set)
X_test <- X_test[,-5]

# Fit
train.lm <- Arima(ts_train, order=c(2,0,2), seasonal=c(0,0,0), xreg=X_train)

# Predict
my.preds <- forecast(train.lm, xreg=X_test, level=c(.95))

# RPMSE
# true: 11.83661
# imputed: 11.59
rpmse <- (test.set[['Crimes']]-my.preds$mean)^2 %>% mean() %>% sqrt()
rpmse
sd(crimes_acf$Crimes)

# Coverage
cvg <- ((test.set[['Crimes']] > my.preds$lower) 
        & (test.set[['Crimes']] < my.preds$upper)) %>% mean()

## Calculate bias
bias <- mean(my.preds$mean-test.set[['Crimes']])
  
## Calculate Width
wid <- (my.preds$upper - my.preds$lower) %>% mean()
wid

# Pseudo R^2
# True: 0.6722103
# Imputed: 0.6669776
# New: 0.7139406
cor(c.lm$residuals, crimes_acf$Crimes)
```

## Inference

```{r}
X_predict <-X[(nrow(X) - 364):nrow(X), ]
my.preds <- forecast(c.lm, xreg=X_predict, level=c(.95))

png("forecast_full.png", width = 10, height = 4, units = "in", res = 300)
plot(my.preds, xaxt = "n")
date_labels <- seq(from = min(crimes_acf$new_date), to = as.Date("2025-02-24"), by = "1 day")
 # Example: labels every month
axis(side = 1, at = date_labels, labels = format(date_labels, "%Y"), cex.axis = 1.45)  # Example: format as "Mon YYYY"

dev.off()


forecast_df <- as.data.frame(my.preds)
dates <- seq(as.Date("2024-02-25"), as.Date("2025-02-23"), by = "day")
date_df <- data.frame(Date = dates)

only_forecast <- ggplot(data = forecast_df,aes(x=date_df$Date)) +
  geom_line(aes(y = `Point Forecast`)) +  # Plot the point forecasts
  geom_ribbon(aes(ymin = `Lo 95`, ymax = `Hi 95`), fill = "dodgerblue", alpha = 0.3) +  # Plot the 95% confidence interval
  labs(x = "Time", y = "Crimes", title = "Forecast Plot")
ggsave("only_forecast.png",only_forecast, width=15)
```



##Coefficient Viz
```{r}
library(GGally)

coef_int <- confint(c.lm)
coef_est <- coef(c.lm)

interval_colors <- ifelse(coef_int[,1] <= 0 & coef_int[,2] >= 0, "black", "blue")



coef_df <- data.frame(
  Coefficient = names(coef_est),
  Estimate = coef_est,
  Lower = coef_int[,1],
  Upper = coef_int[, 2],
  Interval_Color = interval_colors
)


coef_df$Significant <- coef_df$Interval_Color != "black"

# Calculate interval width for sorting purpose
coef_df$IntervalWidth <- abs(coef_df$Upper - coef_df$Lower)

# Step 2: Order 'coef_df' by significance, then by interval width
coef_df_ordered <- coef_df[6:nrow(coef_df), ] %>%
  arrange(Significant, desc(IntervalWidth))

# Convert Coefficient to factor based on the new order to ensure it plots correctly
coef_df_ordered$Coefficient <- factor(coef_df_ordered$Coefficient, levels = unique(coef_df_ordered$Coefficient))

# Step 3: Plot
Confint_Pred_plot <- ggplot(coef_df_ordered, aes(y = Coefficient, x = Estimate, color = Interval_Color)) +
  geom_point(size = 1) +
  geom_segment(aes(x = Lower, xend = Upper, y = Coefficient, yend = Coefficient), size = 1) + 
  labs(title = "Predictor Estimates with 95% Confidence Intervals",
       x = "Estimate",
       y = "Predictor") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "red", size = 1) +
  scale_color_manual(values = c("black" = "black", "blue" = "blue")) +
  theme(legend.position = "none")


ggsave("Confint_Pred_plot.png", Confint_Pred_plot)

```

```{r}
write.csv(crimes_acf, "aggregated_crimes.csv", row.names = FALSE)
```

